[package]
name = "demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.11.3", default_features = false, features = ["wayland"] }
bevy_hanabi = "0.7.0"
bevy_pixel_buffer = "0.5.0"
bevy_pixels = { version = "0.11.0", features = ["wayland"] }
colorgrad = "0.6.2"
nalgebra = "0.32.3"
rayon = "1.8.0"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
