name: build

on: push

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-Gnu-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: tlm_rs
            name: tlm-linux-gnu-x86_64.tar.gz
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: tlm_rs.exe
            name: tlm-windows-x86_64.zip
            command: build

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: tlm_rs
            name: tlm-apple-darwin-x86_64.tar.gz
            command: build

    runs-on: ${{ matrix.platform.os }}
    env: 
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: Swatinem/rust-cache@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          if [[ "${{ matrix.platform.os }}" == "ubuntu-20.04" ]]; then
            sudo apt update
            sudo apt install pkg-config libx11-dev libasound2-dev libudev-dev libxkbcommon-x11-0 libwayland-dev libxkbcommon-dev
          fi
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
          toolchain: stable
      - name: Package as archive
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release
          if [[ "${{ matrix.platform.os }}" == "windows-latest" ]]; then
            7z a ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          else
            tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          fi
          cd -
      - name: Publish release artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.platform.name }}"
          path: "${{ matrix.platform.name }}"
  
