name: build

on: [push, pull_request]

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: FreeBSD-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: tlm
            name: tlm-linux-gnu-x86_64.tar.gz
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: tlm.exe
            name: tlm-windows-x86_64.zip
            command: build

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: tlm
            name: tlm-apple-darwin-x86_64.tar.gz
            command: build

    runs-on: ${{ matrix.platform.os }}
    env: 
      RUSTFLAGS: "-D warnings"
    steps:
      - uses: Swatinem/rust-cache@v2
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--locked --release"
          strip: true
          toolchain: nightly
