name: build

on: [push, pull_request]

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-Gnu-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            bin: tlm
            name: tlm-linux-gnu-x86_64.tar.gz
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: tlm.exe
            name: tlm-windows-x86_64.zip
            command: build

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: tlm
            name: tlm-apple-darwin-x86_64.tar.gz
            command: build

    runs-on: ${{ matrix.platform.os }}
    env: 
      RUSTFLAGS: "-D warnings"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          override: true
          target: ${{ matrix.platform.target }}
        
      - uses: Swatinem/rust-cache@v2
      
      - name: Build target
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target ${{ matrix.platform.target }}

      - name: Package
        shell: bash
        run: |
          cd target/${{ matrix.platform.target }}/release      
          tar czvf ../../../tlm_rs-${{ matrix.platform.target }}.tar.gz tlm_rs
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
            files: 'tlm_rs*'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}